### ISSUE TITLE
reading the contents of the sent packet

### ISSUE THREAD

**Issue by oer2349** [frengor/PacketInjectorAPI#2]
When the packet is sent, i can only get the name of the packet sent, for example, can i read the contents of the package when the custompayload package is sent?

**Comment by frengor** [comment]
You can use the `getPacket()` method to get the NMS packet. Then you need to cast the returned `Object` before you use it.

So, for the custompaylod example, you need to cast the object returned by `getPacket()` to the `CustomPaylodPacket` class (the name is probably wrong, as it's version dependant) and then access the field with the paylod.

Alternatively, you can use the `getValue(fieldName)` method to get the value of the field named `fieldName` inside the NMS packet.

**Comment by oer2349** [comment]
getPacket() i can only get the name of the package sent by the player using can u send me example?

**Comment by frengor** [comment]
No, with `getPacket()` you get the object of the packet:
```java
PacketEventManager eventManager = PacketInjectorPlugin.getInstance().getPacketInjectorAPI().getEventManager();
eventManager.registerPacketReceiveListener(this, event -> {
    // This example is for Spigot 1.18.2
    if (event.getPacketName().equals("PacketPlayInCustomPayload")) { // Execute only for PacketPlayInCustomPayload packets
        PacketPlayInCustomPayload packet = (PacketPlayInCustomPayload) event.getPacket();
        MinecraftKey key = packet.b();
        PacketDataSerializer payload = packet.c();
    }
});
```
or
```java
PacketEventManager eventManager = PacketInjectorPlugin.getInstance().getPacketInjectorAPI().getEventManager();
eventManager.registerPacketReceiveListener(this, event -> {
    // This example is for Spigot 1.18.2
    if (event.getPacketName().equals("PacketPlayInCustomPayload")) { // Execute only for PacketPlayInCustomPayload packets
        MinecraftKey key = (MinecraftKey) event.getValue("c");
        PacketDataSerializer payload = (PacketDataSerializer) event.getValue("d");
    }
});
```
